name: sockets
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    networks:
      - socket-network
    volumes:
      - sockets-data:/var/lib/postgresql/data

volumes:
  sockets-data:
    driver: local
    name: sockets-data

networks:
  socket-network:
    driver: bridge
    name: socket-network
